version: '3.2'

# docker-compose build docker-docker-compose-jdk-11-mvn
services:
  # Java 11
  docker-docker-compose-jdk-11-mvn:
    image: jtim/docker-docker-compose-jdk-mvn:20.10.5-compose-1.28.6-adoptopenjdk-11.0.10_9-maven-3.6.3
    build:
      context: 3.6.3/adoptopenjdk-11.0.10_9

  # Java 8
  docker-docker-compose-jdk-8-mvn:
    image: jtim/docker-docker-compose-jdk-mvn:20.10.2-compose-1.28.0-openjdk-8u252-maven-3.6.3
    build:
      context: 3.6.3/openjdk-8u252